### ISSUE TITLE
Support for MethodType.CLIENT_STREAMING

### ISSUE THREAD

**Issue by queimadus** [eiennohito/grpc-akka-stream-subrepo#1]
Any plans for supporting `io.grpc.MethodDescriptor.MethodType.CLIENT_STREAMING` rpc calls?

**Comment by eiennohito** [comment]
Infrastructure is in place, only a wrapper like https://github.com/eiennohito/grpc-akka-stream-subrepo/blob/master/src/main/scala/org/eiennohito/grpc/stream/impl/client/UnaryCallImpl.scala
and binding like https://github.com/eiennohito/grpc-akka-stream-subrepo/blob/master/src/main/scala/org/eiennohito/grpc/stream/client/AStreamClient.scala#L75 needs to be implemented.

AStream* naming is more problematic and very placeholder-ish. It should be fixed before everything else.

**Comment by queimadus** [comment]
I'm working on [PR (WIP)](https://github.com/eiennohito/grpc-akka-stream-subrepo/compare/master...queimadus:grpc-client-streaming) to address this. Unfortunately, I'm having some trouble understanding on how the client is signalled that the server is ready to receive more messages, to ensure correct flow-control.

In a `CLIENT_STREAMING` call, the server calls `call.request(15)` signalling the client that it is ready to consume messages. How does the client get informed that it has to send 15 messages in response to that request?

At first I thought the `onReady` callback and `call.isReady()` were the way to do this: we could send messages after `onReady` is called and while `calli.Ready` is true. But that does not seem to be the case, as it always `true` even if I artificially force a slow consumer.

**Comment by eiennohito** [comment]
`isReady` and `onReady` is only available public interface for doing this in `grpc-java` I found.

As far as I dug into isReady implementation (for the netty backend), it returns true whether a certain buffer has empty space and false otherwise [somewhere here](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/AbstractStream2.java#L234).

**Comment by eiennohito** [comment]
It seems that `grpc-java` will buffer everything you put in it and send contents as soon as consumer requests something.

**Comment by queimadus** [comment]
I've created an WIP PR #7 so we can discuss this more precisely and you can review it.
