### ISSUE TITLE
Back-pressure throttle test

### ISSUE THREAD

**Issue by queimadus** [eiennohito/grpc-akka-stream-subrepo#3]
I've tweaked some values in the [GrpcBothSidesBackpressure.scala](https://github.com/eiennohito/grpc-akka-stream-subrepo/blob/master/tests/src/test/scala/org/eiennohito/grpc/GrpcBothSidesBackpressure.scala) spec, namely:

```diff
val call = new OneInStreamOutImpl(client, GreeterGrpc.METHOD_SAY_HELLO_SVR_STREAM, defaultOpts)
- val stream = call(HelloRequestStream(500000, "me"))
+ val stream = call(HelloRequestStream(100, "me"))

-val data = stream.throttle(10, 30.milli, 2, ThrottleMode.Shaping).take(100).toMat(Sink.seq)(Keep.right)
+val data = stream.throttle(10, 30.milli, 2, ThrottleMode.Shaping).toMat(Sink.seq)(Keep.right)
val results = Await.result(data.run(), 30.seconds)
results.length shouldBe 100
Service.counter.get should be <= 200L
```

Throttling the grpc connected source makes the spec fail, results.length is never 100.
I would expect that the source would provide the same elements, only slower, when passed though a throttler.

The same changes but removing the `throttle(<low rate>)` work as you would expect.

**Comment by eiennohito** [comment]
This spec checks existence of backpressure transfer through grpc.
Basically, producer should not produce too much as the result. 
Your changes completely remove that check.

**Comment by queimadus** [comment]
Shouldn't `stream.to(Sink.seq)` and `stream.throttle(<low rate>).to(Sink.seq)`, given enough time, return the same values?

**Comment by eiennohito** [comment]
Yes, they should produce the same values (from the value sense).
But throttling the output side simulates the situation when a consumer is much slower than a producer. In that case, backpressure should not allow the producer to overflow the consumer.

**Comment by queimadus** [comment]
I agree with what you said about backpressure! That is why I am finding this behaviour odd 😛 

I think the following spec, which simulates a slow consumer, should pass, but it does not.
```scala
val call = new OneInStreamOutImpl(client, GreeterGrpc.METHOD_SAY_HELLO_SVR_STREAM, defaultOpts)

val stream1 = call(HelloRequestStream(100, "me"))
val data1 = stream1.throttle(10, 30.milli, 1, ThrottleMode.Shaping).toMat(Sink.seq)(Keep.right)
val results1 = Await.result(data1.run(), 30.seconds) // returns 90 ish

val stream2 = call(HelloRequestStream(100, "me"))
val data2 = stream2.toMat(Sink.seq)(Keep.right)
val results2 = Await.result(data2.run(), 30.seconds) // returns 100

results1.length shouldBe results2.length
```
```
[info] BothSidesBackpressure
[info] - do not eat all stream *** FAILED ***
[info]   91 was not equal to 100 (GrpcBothSidesBackpressure.scala:73)
```

**Comment by eiennohito** [comment]
Also, test passes on travis (and my private CI as well).
Maybe the problem is timings and something with thread scheduling on your computer?

**Comment by queimadus** [comment]
They described test above passes? Do you agree with adding this [test](https://github.com/eiennohito/grpc-akka-stream-subrepo/issues/3#issuecomment-273151577) to that spec then?

>A throttle source should produce the same results as a non-throttled one

**Comment by queimadus** [comment]
I've created #9 to check travis result and the [build failed](https://travis-ci.org/eiennohito/grpc-akka-stream-subrepo/builds/193015317#L382).

**Comment by queimadus** [comment]
The problem may lie here: [GrpcClientHandler.scala#L95](https://github.com/eiennohito/grpc-akka-stream-subrepo/blob/master/src/main/scala/org/eiennohito/grpc/stream/impl/client/GrpcClientHandler.scala#L95).

When `onClose` is called, we're completing the stage without checking if there's still messages in our stage's internal `buffer`
